version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  ui:
    build:
      context: ./ui
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://app:3000/api
    volumes:
      - ./ui:/ui
    depends_on:
      - app

volumes:
  postgres:
